experiment_name: '2022_SNPs_Dark_Adapted_Genomes'

config: "config/config.yaml"
samples: "config/samples.tsv"
pacbio_samples: "config/pacbio_samples.tsv"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

input:
  genome_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/NATL2A/NATL2A.fna
  gff_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/NATL2A/NATL2A.gff
  genbank_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/NATL2A/NATL2A.gbff
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_SNPs_Dark_Adapted_Genomes/intermediates
results: /nfs/chisholmlab001/kve/2022_SNPs_Dark_Adapted_Genomes/results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]
