# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
from pathlib import Path
import pandas as pd

configfile: "config/config.yaml"

SAMPLE_TABLE = pd.read_csv(config["samples"], index_col="sample_name", sep="\t")
SAMPLE_TABLE.index = SAMPLE_TABLE.index.map(str)
SAMPLES = SAMPLE_TABLE.index.values

scratch_dir = Path(config["scratch_dir"])
results_dir = Path(config["results"])
scratch_dict = {
    "trimmed_reads": scratch_dir / "1_trimmed_reads", 
    "genome_index": scratch_dir / "2_genome_index",
    "mapped_reads": scratch_dir / "3_mapped_reads",
    "deduped": {
        "bams": scratch_dir / "4_PCR_duplicates_removed" / "bams",
        "metadata": scratch_dir / "4_PCR_duplicates_removed" / "metadata",
        "depth": scratch_dir / "4_PCR_duplicates_removed" / "read_depth",
    },
    "vcfs": scratch_dir / "5_calling_variants",
    "assembly":{
        "spades": scratch_dir / "6_de_novo_assembly" / "spades",
        "flye": scratch_dir / "6_de_novo_assembly" / "flye",
        "ragtag": scratch_dir / "6_de_novo_assembly" / "ragtag"
    },
    "done_files": {
        "index": scratch_dir / "done_files" / "index.done",
        "analysis": scratch_dir / "done_files" / "analysis"
    },
}

results_dict = {
    "raw_data" : {
        "genome_dup_stats": results_dir / 'raw_data' / 'genome_dup_stats',
        "raw_vcfs": results_dir / 'raw_data' / 'vcfs',
        "mummer" : results_dir / 'raw_data' / 'mummer',
    },
    "vcf_compare" : results_dir / "vcf_comparisons",
    "phased_gene_variants" : results_dir / "phased_gene_variants"
}


rule all:
    input:
        directory(results_dict["vcf_compare"]),
        expand(results_dict["raw_data"]["genome_dup_stats"] / "{sample}_genome_bin_stats.tsv", sample=SAMPLES),
        expand(results_dict["raw_data"]["mummer"] / "{sample}.mums", sample=SAMPLES),
        expand(results_dict["phased_gene_variants"] / "{sample}.phased_gene_variants.tsv", sample=SAMPLES)

if config["aligner"] == "hisat2":

    include: "rules/map_reads_hisat2.smk"


if config["aligner"] == "bwa":

    include: "rules/map_reads_bwa.smk"


if config["aligner"] == "bowtie2":

    include: "rules/map_reads_bowtie2.smk"

if config["aligner"] == "pacbio":

    include: "rules/map_reads_bwa_pacbio.smk"

include: "rules/run_trim.smk"


include: "rules/samtools.smk"


include: "rules/remove_PCR_duplicates.smk"


include: "rules/call_variants.smk"


include: "rules/post_analysis.smk"


include: "rules/align_genomes.smk"

if config["aligner"] != "pacbio":
    include: "rules/assembly_illumina.smk"

if config["aligner"] == "pacbio":
    include: "rules/assembly_pacbio.smk"