snakefile: workflow/Snakefile
use-conda: True
conda-frontend: mamba
rerun-incomplete: True
jobs: 5
latency-wait: 30
keep-going: True
configfile: /nfs/chisholmlab001/kve/2022_SNPs_Dark_Adapted_Genomes/reconstructed_lieberman/input_data/config.yaml
cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --partition={resources.partition}
    --ntasks={resources.tasks}
    --mem={resources.mem}
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{wildcards}.out
    --error=logs/{rule}/{wildcards}.err

set-resources:
  - run_mummer:tasks=1
  - run_mummer:mem="1G"

default-resources:
  - time="1-0"
  - partition="sched_mit_chisholm"
  - mem="250G"
  - tasks=20