experiment_name: '2022_De_Novo_Syn_Assembly_Raw_Samples'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

input: 
  genome_ref: /nfs/chisholmlab001/kve/2022_De_Novo_Syn_Assembly/input_data/latest_ancestor/GCF_000179255.1_ASM17925v1_genomic.fna
  gff_ref: /nfs/chisholmlab001/kve/2022_De_Novo_Syn_Assembly/input_data/latest_ancestor/GCF_000179255.1_ASM17925v1_genomic.gff
  genbank_ref: /nfs/chisholmlab001/kve/2022_De_Novo_Syn_Assembly/input_data/latest_ancestor/GCF_000179255.1_ASM17925v1_genomic.gbff
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_De_Novo_Syn_Assembly/variant_calling/Unfiltered_Samples_Intermediates
results: /nfs/chisholmlab001/kve/2022_De_Novo_Syn_Assembly/variant_calling/Unfiltered_Samples_Results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]