experiment_name: '2022_SNPs_Dark_Adapted_Genomes'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' 'bowtie2' (only for Illumina reads, Pacbio is bwa)
# if PacBio is chosen then assembly is performed with flye instead of default SPAdes

mapper: 'bowtie2'

adapter_file: /nfs/chisholmlab001/chisholmlab/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nobackup1/chisholmlab/kve/2022_SNPs_Dark_Adapted_Genomes/intermediates
results: /nfs/chisholmlab001/kve/2022_SNPs_Dark_Adapted_Genomes/results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all',
  ]
