experiment_name: '2022_WH7803_variant_calling_ax_vs_x'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' 'bowtie2' and 'pacbio'
aligner: 'pacbio'

input:
  genome_ref: /nfs/chisholmlab001/kve/2022_WH7803_variant_calling/inputs/axenic_genomics/WH7803ax.fna
  gff_ref: /nfs/chisholmlab001/kve/2022_WH7803_variant_calling/inputs/axenic_genomics/WH7803ax.gff
  genbank_ref: /nfs/chisholmlab001/kve/2022_WH7803_variant_calling/inputs/axenic_genomics/WH7803ax.gbff
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_WH7803_variant_calling/ax_vs_x_intermediates
results: /nfs/chisholmlab001/kve/2022_WH7803_variant_calling/ax_vs_x_results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]
