experiment_name: '2022_Population_Genomics_9313'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' 'bowtie2' (only for Illumina reads)
# if PacBio is chosen then assembly is performed with flye instead of default SPAdes

mapper: 'bowtie2'

input: 
  genome_ref: /nfs/chisholmlab001/chisholmlab/genomic_resources/strains/img_pro_syn/MIT9313_IMG_2606217562/MIT9313_IMG_2606217562.fna
  gff_ref: /nfs/chisholmlab001/chisholmlab/genomic_resources/strains/img_pro_syn/MIT9313_IMG_2606217562/MIT9313_IMG_2606217562.emapper.decorated.gff
  adapter_file: /nfs/chisholmlab001/chisholmlab/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nobackup1/chisholmlab/kve/2022_Population_Genomics_9313/intermediates
results: /nfs/chisholmlab001/kve/2022_Population_Genomics_9313/results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]