experiment_name: '2022_Population_Genomics_9313'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' and 'bowtie2'
aligner: 'bwa'

input: 
  genome_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/MIT9313/MIT9313.fna
  gff_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/MIT9313/MIT9313.gff
  genbank_ref: /nfs/chisholmlab001/kve/genomic_resources/strains/pro/MIT9313/MIT9313.gbff
  adapter_file: /nfs/chisholmlab001/kve/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nfs/chisholmlab001/kve/2022_Population_Genomics_9313/intermediates
results: /nfs/chisholmlab001/kve/2022_Population_Genomics_9313/results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]