experiment_name: '2022_Population_Genomics_RS9916'

config: "config/config.yaml"
samples: "config/samples.tsv"

# options are 'bwa' 'hisat2' 'bowtie2' (only for Illumina reads)
# if PacBio is chosen then assembly is performed with flye instead of default SPAdes

mapper: 'bowtie2'

input: 
  genome_ref: /nfs/chisholmlab001/chisholmlab/genomic_resources/strains/img_pro_syn/RS9916_IMG_2623620281/RS9916_IMG_2623620281.fna
  gff_ref: /nfs/chisholmlab001/chisholmlab/genomic_resources/strains/img_pro_syn/RS9916_IMG_2623620281/RS9916_IMG_2623620281.emapper.decorated.gff
  adapter_file: /nfs/chisholmlab001/chisholmlab/genomic_resources/references/illumina/all_illumina_adapters.fa
scratch_dir: /nobackup1/chisholmlab/kve/2022_Population_Genomics_RS9916/intermediates
results: /nfs/chisholmlab001/kve/2022_Population_Genomics_RS9916/results

variant_calling_methods: [
  'freebayes', 
  'bcftools_standard', 
  'bcftools_all'
  ]